//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABPSD_RAAMEN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int headerID { get; set; }
        public int ramenID { get; set; }
        public int quantity { get; set; }
    
        public virtual header header { get; set; }
        public virtual raman raman { get; set; }
    }
}
