//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABPSD_RAAMEN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class header
    {
        public int Id { get; set; }
        public int customerID { get; set; }
        public int staffID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual detail detail { get; set; }
        public virtual user user { get; set; }
    }
}
