//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABPSD_RAAMEN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class raman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raman()
        {
            this.details = new HashSet<detail>();
        }
    
        public int Id { get; set; }
        public int meatID { get; set; }
        public string name { get; set; }
        public string broth { get; set; }
        public string price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail> details { get; set; }
        public virtual meat meat { get; set; }
    }
}
